shipEmpty = "No one in ship",
shipSingle = "You can not use ship with single person"
shipUnable = "Unable to use ship",
shipRegistered = " registered in ship in ",
shipAlreadyRegistered = " already in ship",
usernameEmpty = "You can not register without username",
shipQuit = " left ship in ",
shipAlreadyQuit = "You was not ship",
shipError = "Unable to quit ship",
shipCleared = "Ship already empty in ",
shipNull = "Ship just cleared in ",
shipAlreadyEmpty = "No one in ship",
shipTitleEmpty = "Ship list in chat: ",
shipTitle = "Ship list in ",
welcomeSet = "Welcome just set in ",
welcomeError = "Unable to set welcome",
welcomeNotSet = "Welcome was not set",
leaveSet = "Leave just set in ",
leaveError = "Unable to set leave",
leaveNotSet = "Leave was not set",
symbolError = "Message should have less than 100 symbols",
coinVar = ["Heads", "Tails"],
tryAns = ["Fail", "Success"],
roulette = [" died", " survived"],
SetLang = "Language was set as ",
locAlUse = "Language is already in use",
LangErr = "The localization is written incorrectly or there is no such localization",
shipAns = ["Couple of the day", "Gays of the day", "Cocks of the day", "Transes of the day", "Slaves of the day",
           "Pornstars of the day", "Ship of the day", "Sluts of the day", "Gaymers of the day", "Retards of the day",
           "'Only friends'", "Niggers of the day", "Was watching Netflix together", "Died together"],
conditionlist = ["Wheres condition?", "Shit, the condition is fucked", "Command cant work without condition",
                 "Condition or die", "Send a condition", "No condition - no answer"],

suicideAns = ["shot himself!", "went to hell!", "died!", "burnt to death!", "drank an acid!",
              "ate uranium!", "just watched tiktok!", "became down!", "got banned by Yfimsky!", "born in Russia!",
              "rm -rf /*!", "has been destroyed!", "just opened gayshit!", "became a bread!", "became a coder!",
              "got in matrix!", "got a flashback!", "died from cringe!", "died from acid!", "overfapped!"],

rlPh = ["Spinning a wheel!", "Spinning a fuckedwheel!", "AAAAAAAAAAAAAAAAAAAAA!", "Magick time!",
        "Whats that button do? FU-"]
